--
-- PostgreSQL database dump
--

\restrict SlaaQ68etFTE3MSy0IFJmDBr4qOATf9vV1LxajJYggRlNpzwwvuo1esU83yaAja

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-07-27 00:33:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 259 (class 1255 OID 16692)
-- Name: sync_booking_status_master(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.sync_booking_status_master() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    SELECT s.id_booking_status INTO NEW.id_booking_status
    FROM t_booking_status s
    WHERE s.bs_code = UPPER(COALESCE(NEW.b_status, 'CONFIRMED'));
    IF NEW.id_booking_status IS NULL THEN
        NEW.id_booking_status := 2;
    END IF;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    "ID_audit_log" bigint NOT NULL,
    a_action character varying(255),
    a_created_at timestamp(6) without time zone,
    a_detail character varying(1000)
);


--
-- TOC entry 218 (class 1259 OID 16394)
-- Name: audit_log_ID_audit_log_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN "ID_audit_log" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."audit_log_ID_audit_log_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: t_advance_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_advance_ledger (
    id_advance_ledger bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    balance_after numeric(38,2) NOT NULL,
    balance_before numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    note character varying(1000),
    ledger_type character varying(255) NOT NULL,
    id_monthly_rent_bill bigint,
    id_guest bigint NOT NULL,
    id_payment bigint,
    id_room bigint
);


--
-- TOC entry 220 (class 1259 OID 16400)
-- Name: t_advance_ledger_id_advance_ledger_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_advance_ledger ALTER COLUMN id_advance_ledger ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_advance_ledger_id_advance_ledger_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: t_app_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_app_setting (
    setting_key character varying(80) NOT NULL,
    setting_label character varying(255) NOT NULL,
    setting_value numeric(12,2) DEFAULT 0 NOT NULL,
    setting_text_value character varying(255)
);


--
-- TOC entry 222 (class 1259 OID 16407)
-- Name: t_bill_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_bill_status (
    id_bill_status bigint NOT NULL,
    bs_name character varying(100) NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16410)
-- Name: t_booking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_booking (
    "ID_booking" bigint NOT NULL,
    b_booking_date date,
    b_check_in_date date,
    b_check_out_date date,
    b_customer_name character varying(255) NOT NULL,
    b_deposit_amount numeric(38,2),
    b_note character varying(1000),
    b_phone character varying(255),
    b_status character varying(255),
    b_stay_type character varying(255),
    "ID_room" bigint,
    "ID_room_type" bigint,
    b_id_card character varying(255),
    b_nationality character varying(255),
    b_booking_number character varying(255),
    id_booking_status bigint
);


--
-- TOC entry 224 (class 1259 OID 16415)
-- Name: t_booking_ID_booking_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_booking ALTER COLUMN "ID_booking" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_booking_ID_booking_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 16679)
-- Name: t_booking_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_booking_status (
    id_booking_status bigint NOT NULL,
    bs_code character varying(30) NOT NULL,
    bs_name character varying(100) NOT NULL,
    bs_name_en character varying(100),
    is_active boolean DEFAULT true NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16416)
-- Name: t_daily_checkout_penalty_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_daily_checkout_penalty_rule (
    "ID_daily_checkout_penalty_rule" bigint NOT NULL,
    start_day_offset integer DEFAULT 0 NOT NULL,
    start_time time without time zone NOT NULL,
    end_day_offset integer,
    end_time time without time zone,
    charge_type character varying(40) NOT NULL,
    charge_value numeric(12,2) DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 16423)
-- Name: t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 226
-- Name: t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq" OWNED BY public.t_daily_checkout_penalty_rule."ID_daily_checkout_penalty_rule";


--
-- TOC entry 227 (class 1259 OID 16424)
-- Name: t_deposit_refund; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deposit_refund (
    "ID_deposit_refund" bigint NOT NULL,
    refund_no character varying(30),
    refund_date date DEFAULT CURRENT_DATE NOT NULL,
    "ID_guest" bigint NOT NULL,
    "ID_room" bigint NOT NULL,
    deposit_amount numeric(12,2) DEFAULT 0 NOT NULL,
    total_deduct_amount numeric(12,2) DEFAULT 0 NOT NULL,
    refund_amount numeric(12,2) DEFAULT 0 NOT NULL,
    extra_charge_amount numeric(12,2) DEFAULT 0 NOT NULL,
    refund_method character varying(255),
    remark character varying(1000),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 228 (class 1259 OID 16435)
-- Name: t_deposit_refund_ID_deposit_refund_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_deposit_refund_ID_deposit_refund_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 228
-- Name: t_deposit_refund_ID_deposit_refund_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_deposit_refund_ID_deposit_refund_seq" OWNED BY public.t_deposit_refund."ID_deposit_refund";


--
-- TOC entry 229 (class 1259 OID 16436)
-- Name: t_deposit_refund_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deposit_refund_item (
    "ID_deposit_refund_item" bigint NOT NULL,
    "ID_deposit_refund" bigint NOT NULL,
    item_name character varying(255) NOT NULL,
    item_amount numeric(12,2) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    item_name_en character varying(255)
);


--
-- TOC entry 230 (class 1259 OID 16443)
-- Name: t_deposit_refund_item_ID_deposit_refund_item_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_deposit_refund_item_ID_deposit_refund_item_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 230
-- Name: t_deposit_refund_item_ID_deposit_refund_item_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_deposit_refund_item_ID_deposit_refund_item_seq" OWNED BY public.t_deposit_refund_item."ID_deposit_refund_item";


--
-- TOC entry 231 (class 1259 OID 16444)
-- Name: t_floor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_floor (
    "ID_floor" bigint NOT NULL,
    f_name character varying(255) NOT NULL,
    f_number integer,
    f_sort_order integer NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 16447)
-- Name: t_floor_ID_floor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_floor ALTER COLUMN "ID_floor" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_floor_ID_floor_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16448)
-- Name: t_gender; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_gender (
    "ID_gender" bigint NOT NULL,
    g_name character varying(255) NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 16451)
-- Name: t_gender_ID_gender_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_gender ALTER COLUMN "ID_gender" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_gender_ID_gender_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16452)
-- Name: t_guest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_guest (
    "ID_guest" bigint NOT NULL,
    g_check_in_date date,
    g_check_out_date date,
    g_full_name character varying(255),
    g_note character varying(1000),
    g_phone character varying(255),
    "ID_room" bigint NOT NULL,
    g_advance_months integer,
    g_deposit numeric(38,2),
    g_price numeric(38,2),
    g_stay_type character varying(255),
    g_initial_payment numeric(38,2),
    g_active boolean,
    g_address character varying(1000),
    g_id_card character varying(255),
    g_total_paid numeric(38,2),
    g_nationality character varying(255),
    g_advance_balance numeric(38,2),
    g_initial_electric_meter numeric(38,2),
    g_initial_water_meter numeric(38,2)
);


--
-- TOC entry 236 (class 1259 OID 16457)
-- Name: t_guest_ID_guest_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_guest ALTER COLUMN "ID_guest" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_guest_ID_guest_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16458)
-- Name: t_menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_menu (
    "ID_menu" bigint NOT NULL,
    m_icon character varying(255) NOT NULL,
    m_link character varying(255),
    m_name character varying(255) NOT NULL,
    m_sort_order integer NOT NULL,
    "ID_parent_menu" bigint,
    m_status character varying(1) DEFAULT 'A'::character varying NOT NULL
);


--
-- TOC entry 238 (class 1259 OID 16463)
-- Name: t_menu_ID_menu_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_menu ALTER COLUMN "ID_menu" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_menu_ID_menu_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16464)
-- Name: t_monthly_rent_bill; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_monthly_rent_bill (
    id_monthly_rent_bill bigint NOT NULL,
    billing_month integer NOT NULL,
    billing_year integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_electric_meter numeric(38,2),
    current_water_meter numeric(38,2),
    discount_amount numeric(38,2),
    due_date date,
    electric_amount numeric(38,2),
    electric_rate numeric(38,2),
    electric_unit numeric(38,2),
    issue_date date,
    note character varying(1000),
    other_amount numeric(38,2),
    previous_electric_meter numeric(38,2),
    previous_water_meter numeric(38,2),
    rent_amount numeric(38,2),
    total_amount numeric(38,2),
    updated_at timestamp(6) without time zone NOT NULL,
    water_amount numeric(38,2),
    water_rate numeric(38,2),
    water_unit numeric(38,2),
    id_guest bigint NOT NULL,
    id_room bigint NOT NULL,
    advance_applied_amount numeric(38,2),
    paid_amount numeric(38,2),
    remaining_amount numeric(38,2),
    subtotal_amount numeric(38,2),
    bill_number character varying(20),
    id_bill_status bigint DEFAULT 1 NOT NULL
);


--
-- TOC entry 240 (class 1259 OID 16470)
-- Name: t_monthly_rent_bill_id_monthly_rent_bill_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_monthly_rent_bill ALTER COLUMN id_monthly_rent_bill ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_monthly_rent_bill_id_monthly_rent_bill_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16471)
-- Name: t_payment_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_payment_detail (
    "ID_payment_detail" bigint NOT NULL,
    "ID_payment" bigint NOT NULL,
    detail_quantity numeric(12,2) DEFAULT 1 NOT NULL,
    detail_unit_price numeric(12,2) DEFAULT 0 NOT NULL,
    detail_amount numeric(12,2) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ID_payment_item" bigint
);


--
-- TOC entry 242 (class 1259 OID 16479)
-- Name: t_payemnt_detail_ID_payemnt_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_payemnt_detail_ID_payemnt_detail_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5182 (class 0 OID 0)
-- Dependencies: 242
-- Name: t_payemnt_detail_ID_payemnt_detail_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_payemnt_detail_ID_payemnt_detail_seq" OWNED BY public.t_payment_detail."ID_payment_detail";


--
-- TOC entry 243 (class 1259 OID 16480)
-- Name: t_payment_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_payment_item (
    "ID_payment_item" bigint NOT NULL,
    item_name character varying(255) NOT NULL,
    item_name_en character varying(255),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 244 (class 1259 OID 16487)
-- Name: t_payemnt_item_ID_payemnt_item_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_payemnt_item_ID_payemnt_item_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5183 (class 0 OID 0)
-- Dependencies: 244
-- Name: t_payemnt_item_ID_payemnt_item_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_payemnt_item_ID_payemnt_item_seq" OWNED BY public.t_payment_item."ID_payment_item";


--
-- TOC entry 245 (class 1259 OID 16488)
-- Name: t_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_payment (
    "ID_payment" bigint NOT NULL,
    p_amount numeric(38,2),
    p_payment_date date,
    p_status character varying(255),
    "ID_room" bigint,
    p_payment_method character varying(255),
    p_remark character varying(1000),
    "ID_guest" bigint,
    p_fine_amount numeric(38,2) DEFAULT 0,
    "ID_reciept" bigint,
    id_monthly_rent_bill bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ID_booking" bigint,
    "ID_deposit_refund" bigint
);


--
-- TOC entry 246 (class 1259 OID 16495)
-- Name: t_payment_ID_payment_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_payment ALTER COLUMN "ID_payment" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_payment_ID_payment_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16496)
-- Name: t_reciept; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_reciept (
    "ID_reciept" bigint NOT NULL,
    rec_date date DEFAULT CURRENT_DATE NOT NULL,
    "ID_rec_type" bigint NOT NULL,
    rec_amount numeric(12,2) DEFAULT 0 NOT NULL,
    rec_no character varying(30),
    "ID_payment" bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 248 (class 1259 OID 16502)
-- Name: t_reciept_ID_reciept_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_reciept_ID_reciept_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5184 (class 0 OID 0)
-- Dependencies: 248
-- Name: t_reciept_ID_reciept_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_reciept_ID_reciept_seq" OWNED BY public.t_reciept."ID_reciept";


--
-- TOC entry 249 (class 1259 OID 16503)
-- Name: t_reciept_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_reciept_type (
    "ID_rec_type" bigint NOT NULL,
    rec_type_name character varying(255) NOT NULL
);


--
-- TOC entry 250 (class 1259 OID 16506)
-- Name: t_room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_room (
    "ID_room" bigint NOT NULL,
    r_monthly_price numeric(38,2),
    r_nightly_price numeric(38,2),
    r_room_number character varying(255) NOT NULL,
    r_room_type character varying(255),
    r_status character varying(255),
    r_floor integer,
    "ID_floor" bigint,
    "ID_room_type" bigint
);


--
-- TOC entry 251 (class 1259 OID 16511)
-- Name: t_room_ID_room_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_room ALTER COLUMN "ID_room" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_room_ID_room_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 16512)
-- Name: t_room_transfer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_room_transfer (
    "ID_room_transfer" bigint NOT NULL,
    "ID_guest" bigint NOT NULL,
    "ID_from_room" bigint NOT NULL,
    "ID_to_room" bigint NOT NULL,
    transfer_date date DEFAULT CURRENT_DATE NOT NULL,
    stay_type character varying(50),
    old_price numeric(12,2) DEFAULT 0 NOT NULL,
    new_price numeric(12,2) DEFAULT 0 NOT NULL,
    remark character varying(1000),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 253 (class 1259 OID 16521)
-- Name: t_room_transfer_ID_room_transfer_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."t_room_transfer_ID_room_transfer_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5185 (class 0 OID 0)
-- Dependencies: 253
-- Name: t_room_transfer_ID_room_transfer_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."t_room_transfer_ID_room_transfer_seq" OWNED BY public.t_room_transfer."ID_room_transfer";


--
-- TOC entry 254 (class 1259 OID 16522)
-- Name: t_room_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_room_type (
    "ID_room_type" bigint NOT NULL,
    rt_detail character varying(1000),
    rt_monthly_price numeric(38,2),
    rt_name character varying(255) NOT NULL,
    rt_nightly_price numeric(38,2)
);


--
-- TOC entry 255 (class 1259 OID 16527)
-- Name: t_room_type_ID_room_type_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_room_type ALTER COLUMN "ID_room_type" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_room_type_ID_room_type_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 16528)
-- Name: t_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_user (
    "ID_user" bigint NOT NULL,
    u_birth_date date,
    u_full_name character varying(255),
    u_password character varying(255) NOT NULL,
    u_username character varying(255) NOT NULL,
    "ID_gender" bigint,
    u_enabled boolean,
    u_role character varying(255)
);


--
-- TOC entry 257 (class 1259 OID 16533)
-- Name: t_user_ID_user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_user ALTER COLUMN "ID_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_user_ID_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4850 (class 2604 OID 16534)
-- Name: t_daily_checkout_penalty_rule ID_daily_checkout_penalty_rule; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_daily_checkout_penalty_rule ALTER COLUMN "ID_daily_checkout_penalty_rule" SET DEFAULT nextval('public."t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq"'::regclass);


--
-- TOC entry 4855 (class 2604 OID 16535)
-- Name: t_deposit_refund ID_deposit_refund; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund ALTER COLUMN "ID_deposit_refund" SET DEFAULT nextval('public."t_deposit_refund_ID_deposit_refund_seq"'::regclass);


--
-- TOC entry 4862 (class 2604 OID 16536)
-- Name: t_deposit_refund_item ID_deposit_refund_item; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund_item ALTER COLUMN "ID_deposit_refund_item" SET DEFAULT nextval('public."t_deposit_refund_item_ID_deposit_refund_item_seq"'::regclass);


--
-- TOC entry 4867 (class 2604 OID 16537)
-- Name: t_payment_detail ID_payment_detail; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_detail ALTER COLUMN "ID_payment_detail" SET DEFAULT nextval('public."t_payemnt_detail_ID_payemnt_detail_seq"'::regclass);


--
-- TOC entry 4873 (class 2604 OID 16538)
-- Name: t_payment_item ID_payment_item; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_item ALTER COLUMN "ID_payment_item" SET DEFAULT nextval('public."t_payemnt_item_ID_payemnt_item_seq"'::regclass);


--
-- TOC entry 4878 (class 2604 OID 16539)
-- Name: t_reciept ID_reciept; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reciept ALTER COLUMN "ID_reciept" SET DEFAULT nextval('public."t_reciept_ID_reciept_seq"'::regclass);


--
-- TOC entry 4882 (class 2604 OID 16540)
-- Name: t_room_transfer ID_room_transfer; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_transfer ALTER COLUMN "ID_room_transfer" SET DEFAULT nextval('public."t_room_transfer_ID_room_transfer_seq"'::regclass);


--
-- TOC entry 5132 (class 0 OID 16389)
-- Dependencies: 217
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.audit_log VALUES (1, 'CHECK_IN', '2026-07-19 23:43:20.411551', 'Room 001 guest Chalantorn Promma-in');
INSERT INTO public.audit_log VALUES (2, 'CHECK_IN', '2026-07-20 00:21:12.246556', 'Room 002 guest Chalantorn Promma-in');
INSERT INTO public.audit_log VALUES (3, 'CHECK_IN', '2026-07-20 00:29:29.853574', 'Room 002 guest Chalantorn Promma-in');
INSERT INTO public.audit_log VALUES (4, 'CHECK_IN', '2026-07-20 01:11:05.378364', 'Room 003 guest Chalantorn Promma-in');
INSERT INTO public.audit_log VALUES (5, 'CHECK_IN', '2026-07-20 02:04:03.866246', 'Room 004 guest Chalantorn Promma-in');
INSERT INTO public.audit_log VALUES (6, 'MONTHLY_RENT_BILL', '2026-07-20 02:59:03.033868', 'Room 002 2026-06 PARTIAL_PAID');
INSERT INTO public.audit_log VALUES (7, 'MONTHLY_RENT_BILL', '2026-07-24 17:28:15.524614', 'Room 002 2026-07 PARTIAL_PAID');
INSERT INTO public.audit_log VALUES (8, 'BOOKING', '2026-07-26 01:39:21.500093', 'Room type ห้องพัดลม เล็ก customer Chalantorn Promma-in');


--
-- TOC entry 5134 (class 0 OID 16395)
-- Dependencies: 219
-- Data for Name: t_advance_ledger; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_advance_ledger VALUES (1, 13500.00, 13500.00, 0.00, '2026-07-20 00:21:12.210457', 'admin', 'รับค่าเช่าล่วงหน้าวันเข้าพัก 13500.00', 'ADD_ADVANCE', NULL, 3, NULL, 2);
INSERT INTO public.t_advance_ledger VALUES (2, 13500.00, 13500.00, 0.00, '2026-07-20 00:29:29.821332', 'admin', 'รับค่าเช่าล่วงหน้าวันเข้าพัก 13500.00', 'ADD_ADVANCE', NULL, 4, NULL, 2);
INSERT INTO public.t_advance_ledger VALUES (3, 27000.00, 27000.00, 0.00, '2026-07-20 01:11:05.345761', 'admin', 'รับค่าเช่าล่วงหน้าวันเข้าพัก 27000.00', 'ADD_ADVANCE', NULL, 5, NULL, 3);
INSERT INTO public.t_advance_ledger VALUES (4, -4500.00, 9000.00, 13500.00, '2026-07-20 02:59:03.000107', 'admin', 'หักเครดิตล่วงหน้าบิล 6/2569', 'APPLY_ADVANCE', 1, 4, NULL, 2);
INSERT INTO public.t_advance_ledger VALUES (5, -4500.00, 4500.00, 9000.00, '2026-07-24 17:28:15.522039', 'admin', 'หักเครดิตล่วงหน้าบิล 7/2569', 'APPLY_ADVANCE', 2, 4, NULL, 2);


--
-- TOC entry 5136 (class 0 OID 16401)
-- Dependencies: 221
-- Data for Name: t_app_setting; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_app_setting VALUES ('electric_rate', 'หน่วยไฟ', 7.00, NULL);
INSERT INTO public.t_app_setting VALUES ('water_rate', 'หน่วยน้ำ', 5.00, NULL);
INSERT INTO public.t_app_setting VALUES ('fine_interval_days', 'รอบวันค่าปรับ', 7.00, NULL);
INSERT INTO public.t_app_setting VALUES ('system_name', 'ชื่อระบบ', 0.00, 'ชื่อโรงแรม/หอพัก');
INSERT INTO public.t_app_setting VALUES ('daily_checkout_time', 'เวลาเช็คเอาต์ห้องพักรายวัน', 0.00, '10:00');
INSERT INTO public.t_app_setting VALUES ('fine_amount', 'ค่าปรับจ่ายบิลล่าช้า', 10.00, NULL);
INSERT INTO public.t_app_setting VALUES ('default_deposit', 'ค่าประกันรายวัน', 1000.00, NULL);
INSERT INTO public.t_app_setting VALUES ('monthly_deposit', 'ค่าประกันรายเดือน', 10000.00, NULL);
INSERT INTO public.t_app_setting VALUES ('checkout_overdue_fine_per_hour', 'ค่าปรับเช็คเอาต์เกินกำหนดต่อชั่วโมง', 0.00, NULL);


--
-- TOC entry 5137 (class 0 OID 16407)
-- Dependencies: 222
-- Data for Name: t_bill_status; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_bill_status VALUES (1, 'รอชำระ');
INSERT INTO public.t_bill_status VALUES (2, 'ชำระบางส่วน');
INSERT INTO public.t_bill_status VALUES (3, 'ชำระครบ');
INSERT INTO public.t_bill_status VALUES (4, 'ยกเลิก');


--
-- TOC entry 5138 (class 0 OID 16410)
-- Dependencies: 223
-- Data for Name: t_booking; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_booking VALUES (1, '2026-07-26', '2026-08-01', '2026-08-07', 'Chalantorn Promma-in', 1000.00, '', '0897654321', 'CONFIRMED', 'DAILY', NULL, 2, '3454545445121', 'ไทย', 'B2026000001', 2);


--
-- TOC entry 5173 (class 0 OID 16679)
-- Dependencies: 258
-- Data for Name: t_booking_status; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_booking_status VALUES (1, 'PENDING', 'รอยืนยัน', 'Pending', true);
INSERT INTO public.t_booking_status VALUES (2, 'CONFIRMED', 'ยืนยันแล้ว', 'Confirmed', true);
INSERT INTO public.t_booking_status VALUES (3, 'CHECKED_IN', 'เข้าพักแล้ว', 'Checked in', true);
INSERT INTO public.t_booking_status VALUES (4, 'CANCELLED', 'ยกเลิก', 'Cancelled', true);


--
-- TOC entry 5140 (class 0 OID 16416)
-- Dependencies: 225
-- Data for Name: t_daily_checkout_penalty_rule; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_daily_checkout_penalty_rule VALUES (1, 0, '11:00:01', 0, '13:00:00', 'PER_HOUR', 50.00, true, 1);
INSERT INTO public.t_daily_checkout_penalty_rule VALUES (2, 0, '13:00:01', 0, '23:59:59', 'ADD_NIGHTS', 0.00, true, 2);


--
-- TOC entry 5142 (class 0 OID 16424)
-- Dependencies: 227
-- Data for Name: t_deposit_refund; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5144 (class 0 OID 16436)
-- Dependencies: 229
-- Data for Name: t_deposit_refund_item; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5146 (class 0 OID 16444)
-- Dependencies: 231
-- Data for Name: t_floor; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_floor VALUES (1, 'ชั้น 1', 1, 10);
INSERT INTO public.t_floor VALUES (2, 'ชั้น 2', 2, 20);


--
-- TOC entry 5148 (class 0 OID 16448)
-- Dependencies: 233
-- Data for Name: t_gender; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_gender VALUES (1, 'ชาย');
INSERT INTO public.t_gender VALUES (2, 'หญิง');
INSERT INTO public.t_gender VALUES (3, 'อื่น ๆ');


--
-- TOC entry 5150 (class 0 OID 16452)
-- Dependencies: 235
-- Data for Name: t_guest; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_guest VALUES (2, '2026-07-19', '2026-07-20', 'Chalantorn Promma-in', '', '0897654321', 1, NULL, 1000.00, 350.00, 'DAILY', 1350.00, true, NULL, '3454545445121', 1350.00, 'ไทย', 0.00, 0.00, 0.00);
INSERT INTO public.t_guest VALUES (3, '2026-07-20', NULL, 'Chalantorn Promma-in', '', '0897654321', 2, 3, 10000.00, 4500.00, 'MONTHLY', 23500.00, true, NULL, '2456787384534', 23500.00, 'ไทย', 13500.00, 0.00, 0.00);
INSERT INTO public.t_guest VALUES (5, '2026-07-20', NULL, 'Chalantorn Promma-in', '', '0897654321', 3, 6, 10000.00, 4500.00, 'MONTHLY', 37000.00, true, NULL, '2456787384534', 37000.00, 'ไทย', 27000.00, 0.00, 0.00);
INSERT INTO public.t_guest VALUES (6, '2026-07-01', '2026-07-10', 'Chalantorn Promma-in', '', '0897654321', 4, NULL, 1000.00, 350.00, 'DAILY', 4150.00, true, NULL, '3454545445121', 4150.00, 'ไทย', 0.00, 0.00, 0.00);
INSERT INTO public.t_guest VALUES (4, '2026-07-20', NULL, 'Chalantorn Promma-in', '', '0897654321', 2, 3, 10000.00, 4500.00, 'MONTHLY', 23500.00, true, NULL, '3454545445121', 23500.00, 'ไทย', 4500.00, 0.00, 0.00);


--
-- TOC entry 5152 (class 0 OID 16458)
-- Dependencies: 237
-- Data for Name: t_menu; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_menu VALUES (9, 'bi-wallet2', NULL, 'การเงิน', 40, NULL, 'A');
INSERT INTO public.t_menu VALUES (12, 'bi-receipt', '/finance/monthly-rent/bills', 'รายการบิลค่าเช่า', 20, 9, 'A');
INSERT INTO public.t_menu VALUES (13, 'bi-credit-card-fill', '/payments', 'รับชำระเงิน', 30, 9, 'A');
INSERT INTO public.t_menu VALUES (1, 'bi-grid-fill', '/', 'แดชบอร์ด', 10, NULL, 'A');
INSERT INTO public.t_menu VALUES (7, 'bi-calendar2-check-fill', '/bookings', 'จองห้องพัก', 20, NULL, 'A');
INSERT INTO public.t_menu VALUES (10, 'bi-calendar2-month', '/finance/monthly-rent/billing', 'คิดเงินค่าเช่ารายเดือน', 10, 9, 'A');
INSERT INTO public.t_menu VALUES (17, 'bi-folder', NULL, 'จัดการห้องพัก', 60, NULL, 'A');
INSERT INTO public.t_menu VALUES (2, 'bi-door-open-fill', '/rooms', 'ห้องพัก', 10, 17, 'A');
INSERT INTO public.t_menu VALUES (6, 'bi-house-door-fill', '/room-types', 'ประเภทห้อง', 20, 17, 'A');
INSERT INTO public.t_menu VALUES (18, 'bi-folder', NULL, 'ตั้งค่าระบบ', 80, NULL, 'A');
INSERT INTO public.t_menu VALUES (16, 'bi bi-gear', '/settings/defaults', 'ตั้งค่าเริ่มต้น', 10, 18, 'A');
INSERT INTO public.t_menu VALUES (5, 'bi-person-badge-fill', '/users', 'ผู้ใช้งาน', 20, 18, 'A');
INSERT INTO public.t_menu VALUES (15, 'bi-list-ol', '/menus/order', 'จัดการลำดับเมนู', 30, 18, 'A');
INSERT INTO public.t_menu VALUES (3, 'bi-clipboard-data', '/guests', 'จัดการการเข้าพัก', 30, NULL, 'A');
INSERT INTO public.t_menu VALUES (22, 'bi-file-earmark-bar-graph', '/reports/rooms', 'รายงานสถานะห้องพัก', 30, 8, 'H');
INSERT INTO public.t_menu VALUES (8, 'bi-bar-chart-line', NULL, 'รายงาน', 70, NULL, 'A');
INSERT INTO public.t_menu VALUES (20, 'bi-file-earmark-bar-graph', '/reports/revenue', 'รายงานรายได้', 10, 8, 'A');
INSERT INTO public.t_menu VALUES (21, 'bi-file-earmark-bar-graph', '/reports/monthly-bills', 'รายงานใบแจ้งค่าเช่า', 20, 8, 'A');
INSERT INTO public.t_menu VALUES (23, 'bi-file-earmark-bar-graph', '/reports/bookings', 'รายงานการจอง', 40, 8, 'A');
INSERT INTO public.t_menu VALUES (24, 'bi-file-earmark-bar-graph', '/reports/deposit-refunds', 'รายงานคืนเงินประกัน', 50, 8, 'A');
INSERT INTO public.t_menu VALUES (19, 'bi-arrow-counterclockwise', '/finance/deposit-refunds', 'รายการคืนเงินประกัน', 40, 9, 'A');


--
-- TOC entry 5154 (class 0 OID 16464)
-- Dependencies: 239
-- Data for Name: t_monthly_rent_bill; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_monthly_rent_bill VALUES (1, 6, 2026, '2026-07-20 02:59:02.930101', 35.00, 15.00, 0.00, '2026-07-25', 245.00, 7.00, 35.00, '2026-07-20', '', 0.00, 0.00, 0.00, 4500.00, 320.00, '2026-07-20 02:59:03.065766', 75.00, 5.00, 15.00, 4, 2, 4500.00, 0.00, 320.00, 4820.00, 'M2026000001', 2);
INSERT INTO public.t_monthly_rent_bill VALUES (2, 7, 2026, '2026-07-24 17:28:15.455684', 45.00, 55.00, 0.00, '2026-07-29', 70.00, 7.00, 10.00, '2026-07-24', '', 0.00, 35.00, 15.00, 4500.00, 270.00, '2026-07-24 17:28:15.530667', 200.00, 5.00, 40.00, 4, 2, 4500.00, 0.00, 270.00, 4770.00, 'M2026000002', 2);


--
-- TOC entry 5160 (class 0 OID 16488)
-- Dependencies: 245
-- Data for Name: t_payment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_payment VALUES (2, 1350.00, '2026-07-19', 'PAID', 1, 'เงินสด', NULL, 2, 0.00, 2, NULL, '2026-07-19 23:43:20.118462', NULL, NULL);
INSERT INTO public.t_payment VALUES (4, 23500.00, '2026-07-20', 'PAID', 2, 'เงินสด', NULL, 4, 0.00, 4, NULL, '2026-07-20 00:29:29.442969', NULL, NULL);
INSERT INTO public.t_payment VALUES (5, 37000.00, '2026-07-20', 'PAID', 3, 'เงินสด', NULL, 5, 0.00, 5, NULL, '2026-07-20 01:11:05.035438', NULL, NULL);
INSERT INTO public.t_payment VALUES (6, 4150.00, '2026-07-01', 'PAID', 4, 'เงินสด', NULL, 6, 0.00, 6, NULL, '2026-07-20 02:04:03.543818', NULL, NULL);
INSERT INTO public.t_payment VALUES (7, 1000.00, '2026-07-26', 'PAID', NULL, 'เงินสด', NULL, NULL, 0.00, 7, NULL, '2026-07-26 01:39:21.446753', 1, NULL);


--
-- TOC entry 5156 (class 0 OID 16471)
-- Dependencies: 241
-- Data for Name: t_payment_detail; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_payment_detail VALUES (1, 2, 1.00, 350.00, 350.00, 1, '2026-07-19 23:43:20.280278', 2);
INSERT INTO public.t_payment_detail VALUES (2, 2, 1.00, 1000.00, 1000.00, 2, '2026-07-19 23:43:20.348656', 8);
INSERT INTO public.t_payment_detail VALUES (4, 4, 3.00, 4500.00, 13500.00, 1, '2026-07-20 00:29:29.652352', 137);
INSERT INTO public.t_payment_detail VALUES (5, 4, 1.00, 10000.00, 10000.00, 2, '2026-07-20 00:29:29.75105', 8);
INSERT INTO public.t_payment_detail VALUES (6, 5, 6.00, 4500.00, 27000.00, 1, '2026-07-20 01:11:05.210267', 137);
INSERT INTO public.t_payment_detail VALUES (7, 5, 1.00, 10000.00, 10000.00, 2, '2026-07-20 01:11:05.276482', 8);
INSERT INTO public.t_payment_detail VALUES (8, 6, 9.00, 350.00, 3150.00, 1, '2026-07-20 02:04:03.735266', 2);
INSERT INTO public.t_payment_detail VALUES (9, 6, 1.00, 1000.00, 1000.00, 2, '2026-07-20 02:04:03.7995', 8);
INSERT INTO public.t_payment_detail VALUES (10, 7, 1.00, 1000.00, 1000.00, 1, '2026-07-26 01:39:21.485697', 10);


--
-- TOC entry 5158 (class 0 OID 16480)
-- Dependencies: 243
-- Data for Name: t_payment_item; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_payment_item VALUES (1, 'ค่าเช่ารายเดือน', 'Monthly rent', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (2, 'ค่าห้องรายวัน', 'Daily room charge', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (3, 'ค่าน้ำ', 'Water charge', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (4, 'ค่าไฟ', 'Electricity charge', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (5, 'ค่าอื่น ๆ', 'Other charge', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (6, 'ส่วนลด', 'Discount', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (7, 'หักเงินล่วงหน้า', 'Advance payment deduction', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (8, 'ค่าประกัน', 'Deposit', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (9, 'หักค่าประกัน', 'Deposit deduction', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (10, 'มัดจำจองห้อง', 'Booking deposit', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (11, 'หักมัดจำจอง', 'Booking deposit deduction', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (12, 'ค่าบริการของลูกค้ารายวัน', 'Daily guest service', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (13, 'ค่าปรับ', 'Penalty', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (14, 'ค่าปรับเช็กเอาต์ล่าช้า', 'Late check-out penalty', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (15, 'ค่าเสียหาย', 'Damage charge', true, '2026-07-19 15:34:02.144962');
INSERT INTO public.t_payment_item VALUES (121, 'ค่าแรกเข้า รายเดือน', 'Service charge', true, '2026-07-20 00:21:12.139194');
INSERT INTO public.t_payment_item VALUES (137, 'ชำระค่าห้องล่วงหน้า', 'Advance room payment', true, '2026-07-20 00:29:29.685022');


--
-- TOC entry 5162 (class 0 OID 16496)
-- Dependencies: 247
-- Data for Name: t_reciept; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_reciept VALUES (2, '2026-07-19', 2, 1350.00, 'P2026000001', 2, '2026-07-19 23:43:20.149363');
INSERT INTO public.t_reciept VALUES (4, '2026-07-20', 1, 23500.00, 'P2026000002', 4, '2026-07-20 00:29:29.477115');
INSERT INTO public.t_reciept VALUES (6, '2026-07-20', 2, 4150.00, 'P2026000004', NULL, '2026-07-20 02:04:03.576148');
INSERT INTO public.t_reciept VALUES (5, '2026-07-20', 1, 37000.00, 'P2026000003', 5, '2026-07-20 01:11:05.070301');
INSERT INTO public.t_reciept VALUES (7, '2026-07-26', 4, 1000.00, 'P2026000005', 7, '2026-07-26 01:39:21.456285');


--
-- TOC entry 5164 (class 0 OID 16503)
-- Dependencies: 249
-- Data for Name: t_reciept_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_reciept_type VALUES (1, 'ค่าแรกเข้า รายเดือน');
INSERT INTO public.t_reciept_type VALUES (2, 'ค่าบริการของลูกค้ารายวัน');
INSERT INTO public.t_reciept_type VALUES (3, 'ค่าเช่ารายเดือน');
INSERT INTO public.t_reciept_type VALUES (4, 'มัดจำจองห้อง');
INSERT INTO public.t_reciept_type VALUES (5, 'ค่าปรับ');


--
-- TOC entry 5165 (class 0 OID 16506)
-- Dependencies: 250
-- Data for Name: t_room; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_room VALUES (10, 6500.00, 500.00, '010', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (5, 6500.00, 500.00, '005', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (12, 9000.00, 750.00, '202', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (11, 9000.00, 750.00, '201', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (6, 6500.00, 500.00, '006', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (7, 6500.00, 500.00, '007', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (8, 6500.00, 500.00, '008', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (9, 6500.00, 500.00, '009', 'Standard', 'AVAILABLE', NULL, 1, 1);
INSERT INTO public.t_room VALUES (13, 9000.00, 750.00, '203', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (14, 9000.00, 750.00, '204', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (15, 9000.00, 750.00, '205', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (16, 9000.00, 750.00, '206', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (17, 9000.00, 750.00, '207', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (18, 9000.00, 750.00, '208', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (19, 9000.00, 750.00, '209', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (20, 9000.00, 750.00, '210', 'Deluxe', 'AVAILABLE', NULL, 2, 2);
INSERT INTO public.t_room VALUES (1, 6500.00, 500.00, '001', 'Standard', 'DAILY_OCCUPIED', NULL, 1, 1);
INSERT INTO public.t_room VALUES (2, 6500.00, 500.00, '002', 'Standard', 'MONTHLY_OCCUPIED', NULL, 1, 1);
INSERT INTO public.t_room VALUES (3, 6500.00, 500.00, '003', 'Standard', 'MONTHLY_OCCUPIED', NULL, 1, 1);
INSERT INTO public.t_room VALUES (4, 4500.00, 350.00, '004', 'Standard', 'DAILY_OCCUPIED', NULL, 1, 1);


--
-- TOC entry 5167 (class 0 OID 16512)
-- Dependencies: 252
-- Data for Name: t_room_transfer; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 5169 (class 0 OID 16522)
-- Dependencies: 254
-- Data for Name: t_room_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_room_type VALUES (2, '', 3500.00, 'ห้องพัดลม เล็ก', 250.00);
INSERT INTO public.t_room_type VALUES (1, '', 4500.00, 'ห้องพัดลม ใหญ่', 350.00);


--
-- TOC entry 5171 (class 0 OID 16528)
-- Dependencies: 256
-- Data for Name: t_user; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.t_user VALUES (1, '1990-01-01', 'ผู้ดูแลระบบ', '$2a$10$g3oZwN7UPlbdqZat3fuSNegvrQQHUYFx9YmvKKsMOX34C83/V36v.', 'admin', 3, true, 'ADMIN');


--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 218
-- Name: audit_log_ID_audit_log_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."audit_log_ID_audit_log_seq"', 8, true);


--
-- TOC entry 5187 (class 0 OID 0)
-- Dependencies: 220
-- Name: t_advance_ledger_id_advance_ledger_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.t_advance_ledger_id_advance_ledger_seq', 5, true);


--
-- TOC entry 5188 (class 0 OID 0)
-- Dependencies: 224
-- Name: t_booking_ID_booking_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_booking_ID_booking_seq"', 1, true);


--
-- TOC entry 5189 (class 0 OID 0)
-- Dependencies: 226
-- Name: t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_daily_checkout_penalty_rule_ID_daily_checkout_penalty_rul_seq"', 2, true);


--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 228
-- Name: t_deposit_refund_ID_deposit_refund_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_deposit_refund_ID_deposit_refund_seq"', 1, false);


--
-- TOC entry 5191 (class 0 OID 0)
-- Dependencies: 230
-- Name: t_deposit_refund_item_ID_deposit_refund_item_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_deposit_refund_item_ID_deposit_refund_item_seq"', 1, false);


--
-- TOC entry 5192 (class 0 OID 0)
-- Dependencies: 232
-- Name: t_floor_ID_floor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_floor_ID_floor_seq"', 2, true);


--
-- TOC entry 5193 (class 0 OID 0)
-- Dependencies: 234
-- Name: t_gender_ID_gender_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_gender_ID_gender_seq"', 3, true);


--
-- TOC entry 5194 (class 0 OID 0)
-- Dependencies: 236
-- Name: t_guest_ID_guest_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_guest_ID_guest_seq"', 6, true);


--
-- TOC entry 5195 (class 0 OID 0)
-- Dependencies: 238
-- Name: t_menu_ID_menu_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_menu_ID_menu_seq"', 856, true);


--
-- TOC entry 5196 (class 0 OID 0)
-- Dependencies: 240
-- Name: t_monthly_rent_bill_id_monthly_rent_bill_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.t_monthly_rent_bill_id_monthly_rent_bill_seq', 2, true);


--
-- TOC entry 5197 (class 0 OID 0)
-- Dependencies: 242
-- Name: t_payemnt_detail_ID_payemnt_detail_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_payemnt_detail_ID_payemnt_detail_seq"', 10, true);


--
-- TOC entry 5198 (class 0 OID 0)
-- Dependencies: 244
-- Name: t_payemnt_item_ID_payemnt_item_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_payemnt_item_ID_payemnt_item_seq"', 1232, true);


--
-- TOC entry 5199 (class 0 OID 0)
-- Dependencies: 246
-- Name: t_payment_ID_payment_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_payment_ID_payment_seq"', 7, true);


--
-- TOC entry 5200 (class 0 OID 0)
-- Dependencies: 248
-- Name: t_reciept_ID_reciept_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_reciept_ID_reciept_seq"', 7, true);


--
-- TOC entry 5201 (class 0 OID 0)
-- Dependencies: 251
-- Name: t_room_ID_room_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_room_ID_room_seq"', 21, true);


--
-- TOC entry 5202 (class 0 OID 0)
-- Dependencies: 253
-- Name: t_room_transfer_ID_room_transfer_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_room_transfer_ID_room_transfer_seq"', 1, false);


--
-- TOC entry 5203 (class 0 OID 0)
-- Dependencies: 255
-- Name: t_room_type_ID_room_type_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_room_type_ID_room_type_seq"', 8, true);


--
-- TOC entry 5204 (class 0 OID 0)
-- Dependencies: 257
-- Name: t_user_ID_user_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."t_user_ID_user_seq"', 1, true);


--
-- TOC entry 4889 (class 2606 OID 16542)
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY ("ID_audit_log");


--
-- TOC entry 4891 (class 2606 OID 16544)
-- Name: t_advance_ledger t_advance_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_advance_ledger
    ADD CONSTRAINT t_advance_ledger_pkey PRIMARY KEY (id_advance_ledger);


--
-- TOC entry 4893 (class 2606 OID 16546)
-- Name: t_app_setting t_app_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_app_setting
    ADD CONSTRAINT t_app_setting_pkey PRIMARY KEY (setting_key);


--
-- TOC entry 4895 (class 2606 OID 16548)
-- Name: t_bill_status t_bill_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_bill_status
    ADD CONSTRAINT t_bill_status_pkey PRIMARY KEY (id_bill_status);


--
-- TOC entry 4899 (class 2606 OID 16550)
-- Name: t_booking t_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_booking
    ADD CONSTRAINT t_booking_pkey PRIMARY KEY ("ID_booking");


--
-- TOC entry 4971 (class 2606 OID 16686)
-- Name: t_booking_status t_booking_status_bs_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_booking_status
    ADD CONSTRAINT t_booking_status_bs_code_key UNIQUE (bs_code);


--
-- TOC entry 4973 (class 2606 OID 16684)
-- Name: t_booking_status t_booking_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_booking_status
    ADD CONSTRAINT t_booking_status_pkey PRIMARY KEY (id_booking_status);


--
-- TOC entry 4904 (class 2606 OID 16552)
-- Name: t_daily_checkout_penalty_rule t_daily_checkout_penalty_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_daily_checkout_penalty_rule
    ADD CONSTRAINT t_daily_checkout_penalty_rule_pkey PRIMARY KEY ("ID_daily_checkout_penalty_rule");


--
-- TOC entry 4914 (class 2606 OID 16554)
-- Name: t_deposit_refund_item t_deposit_refund_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund_item
    ADD CONSTRAINT t_deposit_refund_item_pkey PRIMARY KEY ("ID_deposit_refund_item");


--
-- TOC entry 4908 (class 2606 OID 16556)
-- Name: t_deposit_refund t_deposit_refund_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund
    ADD CONSTRAINT t_deposit_refund_pkey PRIMARY KEY ("ID_deposit_refund");


--
-- TOC entry 4910 (class 2606 OID 16558)
-- Name: t_deposit_refund t_deposit_refund_refund_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund
    ADD CONSTRAINT t_deposit_refund_refund_no_key UNIQUE (refund_no);


--
-- TOC entry 4916 (class 2606 OID 16560)
-- Name: t_floor t_floor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_floor
    ADD CONSTRAINT t_floor_pkey PRIMARY KEY ("ID_floor");


--
-- TOC entry 4918 (class 2606 OID 16562)
-- Name: t_gender t_gender_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_gender
    ADD CONSTRAINT t_gender_pkey PRIMARY KEY ("ID_gender");


--
-- TOC entry 4922 (class 2606 OID 16564)
-- Name: t_guest t_guest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_guest
    ADD CONSTRAINT t_guest_pkey PRIMARY KEY ("ID_guest");


--
-- TOC entry 4924 (class 2606 OID 16566)
-- Name: t_menu t_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_menu
    ADD CONSTRAINT t_menu_pkey PRIMARY KEY ("ID_menu");


--
-- TOC entry 4928 (class 2606 OID 16568)
-- Name: t_monthly_rent_bill t_monthly_rent_bill_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_monthly_rent_bill
    ADD CONSTRAINT t_monthly_rent_bill_pkey PRIMARY KEY (id_monthly_rent_bill);


--
-- TOC entry 4937 (class 2606 OID 16570)
-- Name: t_payment_detail t_payemnt_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_detail
    ADD CONSTRAINT t_payemnt_detail_pkey PRIMARY KEY ("ID_payment_detail");


--
-- TOC entry 4939 (class 2606 OID 16572)
-- Name: t_payment_item t_payemnt_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_item
    ADD CONSTRAINT t_payemnt_item_pkey PRIMARY KEY ("ID_payment_item");


--
-- TOC entry 4946 (class 2606 OID 16574)
-- Name: t_payment t_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment
    ADD CONSTRAINT t_payment_pkey PRIMARY KEY ("ID_payment");


--
-- TOC entry 4949 (class 2606 OID 16576)
-- Name: t_reciept t_reciept_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reciept
    ADD CONSTRAINT t_reciept_pkey PRIMARY KEY ("ID_reciept");


--
-- TOC entry 4952 (class 2606 OID 16578)
-- Name: t_reciept_type t_reciept_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reciept_type
    ADD CONSTRAINT t_reciept_type_pkey PRIMARY KEY ("ID_rec_type");


--
-- TOC entry 4954 (class 2606 OID 16580)
-- Name: t_room t_room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room
    ADD CONSTRAINT t_room_pkey PRIMARY KEY ("ID_room");


--
-- TOC entry 4961 (class 2606 OID 16582)
-- Name: t_room_transfer t_room_transfer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_transfer
    ADD CONSTRAINT t_room_transfer_pkey PRIMARY KEY ("ID_room_transfer");


--
-- TOC entry 4963 (class 2606 OID 16584)
-- Name: t_room_type t_room_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_type
    ADD CONSTRAINT t_room_type_pkey PRIMARY KEY ("ID_room_type");


--
-- TOC entry 4967 (class 2606 OID 16586)
-- Name: t_user t_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_user
    ADD CONSTRAINT t_user_pkey PRIMARY KEY ("ID_user");


--
-- TOC entry 4926 (class 2606 OID 16588)
-- Name: t_menu uk4vl3g4iqnlirw5xm93m8bi5np; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_menu
    ADD CONSTRAINT uk4vl3g4iqnlirw5xm93m8bi5np UNIQUE (m_link);


--
-- TOC entry 4920 (class 2606 OID 16590)
-- Name: t_gender uk81sh4ctibvs7ms9vw1rp0h1au; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_gender
    ADD CONSTRAINT uk81sh4ctibvs7ms9vw1rp0h1au UNIQUE (g_name);


--
-- TOC entry 4930 (class 2606 OID 16592)
-- Name: t_monthly_rent_bill uk_monthly_rent_bill_bill_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_monthly_rent_bill
    ADD CONSTRAINT uk_monthly_rent_bill_bill_number UNIQUE (bill_number);


--
-- TOC entry 4932 (class 2606 OID 16594)
-- Name: t_monthly_rent_bill uk_monthly_rent_bill_room_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_monthly_rent_bill
    ADD CONSTRAINT uk_monthly_rent_bill_room_period UNIQUE (id_room, billing_month, billing_year);


--
-- TOC entry 4965 (class 2606 OID 16596)
-- Name: t_room_type ukbwu6m63wv0tfrub1ixsymfvo4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_type
    ADD CONSTRAINT ukbwu6m63wv0tfrub1ixsymfvo4 UNIQUE (rt_name);


--
-- TOC entry 4969 (class 2606 OID 16598)
-- Name: t_user ukfyrnmrbkjida4jgw4y03naup6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_user
    ADD CONSTRAINT ukfyrnmrbkjida4jgw4y03naup6 UNIQUE (u_username);


--
-- TOC entry 4901 (class 2606 OID 16600)
-- Name: t_booking ukgk020u4porwqkicmmu4vbyq0d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_booking
    ADD CONSTRAINT ukgk020u4porwqkicmmu4vbyq0d UNIQUE (b_booking_number);


--
-- TOC entry 4956 (class 2606 OID 16602)
-- Name: t_room ukp60k5qc0y128g341x8ytodx25; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room
    ADD CONSTRAINT ukp60k5qc0y128g341x8ytodx25 UNIQUE (r_room_number);


--
-- TOC entry 4902 (class 1259 OID 16603)
-- Name: ix_daily_checkout_penalty_rule_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_checkout_penalty_rule_sort ON public.t_daily_checkout_penalty_rule USING btree (sort_order);


--
-- TOC entry 4897 (class 1259 OID 16694)
-- Name: ix_t_booking_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_booking_status ON public.t_booking USING btree (id_booking_status);


--
-- TOC entry 4905 (class 1259 OID 16604)
-- Name: ix_t_deposit_refund_guest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_deposit_refund_guest ON public.t_deposit_refund USING btree ("ID_guest");


--
-- TOC entry 4912 (class 1259 OID 16605)
-- Name: ix_t_deposit_refund_item_refund; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_deposit_refund_item_refund ON public.t_deposit_refund_item USING btree ("ID_deposit_refund");


--
-- TOC entry 4906 (class 1259 OID 16606)
-- Name: ix_t_deposit_refund_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_deposit_refund_room ON public.t_deposit_refund USING btree ("ID_room");


--
-- TOC entry 4933 (class 1259 OID 16607)
-- Name: ix_t_payemnt_detail_payment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payemnt_detail_payment ON public.t_payment_detail USING btree ("ID_payment");


--
-- TOC entry 4941 (class 1259 OID 16608)
-- Name: ix_t_payment_booking; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_booking ON public.t_payment USING btree ("ID_booking");


--
-- TOC entry 4942 (class 1259 OID 16609)
-- Name: ix_t_payment_deposit_refund; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_deposit_refund ON public.t_payment USING btree ("ID_deposit_refund");


--
-- TOC entry 4934 (class 1259 OID 16610)
-- Name: ix_t_payment_detail_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_detail_item ON public.t_payment_detail USING btree ("ID_payment_item");


--
-- TOC entry 4935 (class 1259 OID 16611)
-- Name: ix_t_payment_detail_payment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_detail_payment ON public.t_payment_detail USING btree ("ID_payment");


--
-- TOC entry 4943 (class 1259 OID 16612)
-- Name: ix_t_payment_monthly_bill; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_monthly_bill ON public.t_payment USING btree (id_monthly_rent_bill);


--
-- TOC entry 4944 (class 1259 OID 16613)
-- Name: ix_t_payment_reciept; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_payment_reciept ON public.t_payment USING btree ("ID_reciept");


--
-- TOC entry 4947 (class 1259 OID 16614)
-- Name: ix_t_reciept_payment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_reciept_payment ON public.t_reciept USING btree ("ID_payment");


--
-- TOC entry 4957 (class 1259 OID 16615)
-- Name: ix_t_room_transfer_from_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_room_transfer_from_room ON public.t_room_transfer USING btree ("ID_from_room");


--
-- TOC entry 4958 (class 1259 OID 16616)
-- Name: ix_t_room_transfer_guest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_room_transfer_guest ON public.t_room_transfer USING btree ("ID_guest");


--
-- TOC entry 4959 (class 1259 OID 16617)
-- Name: ix_t_room_transfer_to_room; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_t_room_transfer_to_room ON public.t_room_transfer USING btree ("ID_to_room");


--
-- TOC entry 4896 (class 1259 OID 16618)
-- Name: uk_t_bill_status_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_t_bill_status_id ON public.t_bill_status USING btree (id_bill_status);


--
-- TOC entry 4911 (class 1259 OID 16619)
-- Name: ux_t_deposit_refund_no; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_t_deposit_refund_no ON public.t_deposit_refund USING btree (refund_no);


--
-- TOC entry 4940 (class 1259 OID 16620)
-- Name: ux_t_payment_item_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_t_payment_item_name ON public.t_payment_item USING btree (item_name);


--
-- TOC entry 4950 (class 1259 OID 16621)
-- Name: ux_t_reciept_rec_no; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_t_reciept_rec_no ON public.t_reciept USING btree (rec_no);


--
-- TOC entry 4986 (class 2620 OID 16697)
-- Name: t_booking trg_sync_booking_status_master; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_sync_booking_status_master BEFORE INSERT OR UPDATE OF b_status ON public.t_booking FOR EACH ROW EXECUTE FUNCTION public.sync_booking_status_master();


--
-- TOC entry 4974 (class 2606 OID 16687)
-- Name: t_booking fk_t_booking_status; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_booking
    ADD CONSTRAINT fk_t_booking_status FOREIGN KEY (id_booking_status) REFERENCES public.t_booking_status(id_booking_status);


--
-- TOC entry 4980 (class 2606 OID 16622)
-- Name: t_payment fk_t_payment_booking; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment
    ADD CONSTRAINT fk_t_payment_booking FOREIGN KEY ("ID_booking") REFERENCES public.t_booking("ID_booking");


--
-- TOC entry 4981 (class 2606 OID 16627)
-- Name: t_payment fk_t_payment_deposit_refund; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment
    ADD CONSTRAINT fk_t_payment_deposit_refund FOREIGN KEY ("ID_deposit_refund") REFERENCES public.t_deposit_refund("ID_deposit_refund");


--
-- TOC entry 4978 (class 2606 OID 16632)
-- Name: t_payment_detail fk_t_payment_detail_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_detail
    ADD CONSTRAINT fk_t_payment_detail_item FOREIGN KEY ("ID_payment_item") REFERENCES public.t_payment_item("ID_payment_item");


--
-- TOC entry 4975 (class 2606 OID 16637)
-- Name: t_deposit_refund t_deposit_refund_ID_guest_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund
    ADD CONSTRAINT "t_deposit_refund_ID_guest_fkey" FOREIGN KEY ("ID_guest") REFERENCES public.t_guest("ID_guest");


--
-- TOC entry 4976 (class 2606 OID 16642)
-- Name: t_deposit_refund t_deposit_refund_ID_room_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund
    ADD CONSTRAINT "t_deposit_refund_ID_room_fkey" FOREIGN KEY ("ID_room") REFERENCES public.t_room("ID_room");


--
-- TOC entry 4977 (class 2606 OID 16647)
-- Name: t_deposit_refund_item t_deposit_refund_item_ID_deposit_refund_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deposit_refund_item
    ADD CONSTRAINT "t_deposit_refund_item_ID_deposit_refund_fkey" FOREIGN KEY ("ID_deposit_refund") REFERENCES public.t_deposit_refund("ID_deposit_refund") ON DELETE CASCADE;


--
-- TOC entry 4979 (class 2606 OID 16652)
-- Name: t_payment_detail t_payemnt_detail_ID_payment_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_payment_detail
    ADD CONSTRAINT "t_payemnt_detail_ID_payment_fkey" FOREIGN KEY ("ID_payment") REFERENCES public.t_payment("ID_payment");


--
-- TOC entry 4982 (class 2606 OID 16657)
-- Name: t_reciept t_reciept_ID_rec_type_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reciept
    ADD CONSTRAINT "t_reciept_ID_rec_type_fkey" FOREIGN KEY ("ID_rec_type") REFERENCES public.t_reciept_type("ID_rec_type");


--
-- TOC entry 4983 (class 2606 OID 16662)
-- Name: t_room_transfer t_room_transfer_ID_from_room_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_transfer
    ADD CONSTRAINT "t_room_transfer_ID_from_room_fkey" FOREIGN KEY ("ID_from_room") REFERENCES public.t_room("ID_room");


--
-- TOC entry 4984 (class 2606 OID 16667)
-- Name: t_room_transfer t_room_transfer_ID_guest_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_transfer
    ADD CONSTRAINT "t_room_transfer_ID_guest_fkey" FOREIGN KEY ("ID_guest") REFERENCES public.t_guest("ID_guest");


--
-- TOC entry 4985 (class 2606 OID 16672)
-- Name: t_room_transfer t_room_transfer_ID_to_room_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_room_transfer
    ADD CONSTRAINT "t_room_transfer_ID_to_room_fkey" FOREIGN KEY ("ID_to_room") REFERENCES public.t_room("ID_room");


-- Completed on 2026-07-27 00:33:09

--
-- PostgreSQL database dump complete
--

\unrestrict SlaaQ68etFTE3MSy0IFJmDBr4qOATf9vV1LxajJYggRlNpzwwvuo1esU83yaAja

